### ISSUE TITLE
Cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by rochapablo** [hughsk/atom-define-jump#1]
1. Go to declaration
2. Try use the kaymap

```
'atom-workspace':
  'alt-g': 'define-jump:to-original-definition'
```

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [define-jump](git://github.com/hughsk/atom-define-jump) package, v1.0.1
### Stack Trace

Failed to activate the define-jump package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.activate (...\.atom\packages\define-jump\index.js:15:21)
  at Package.module.exports.Package.activateNow (...\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
  at ...\atom\app-1.0.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (...\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (...\atom\app-1.0.0\resources\app.asar\src\command-registry.js:222:20)
  at ...\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (...\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (...\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at KeymapManager.module.exports.KeymapManager.terminatePendingState (...\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:503:14)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (...\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:393:21)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (...\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```
### Commands

```
     -0:47.6.0 settings-view:open (atom-text-editor.editor.is-focused)
 22x -0:12.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
  2x -0:10.6.0 define-jump:to-original-definition (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
define-jump, v1.0.1
goto, vundefined
linter, v1.1.0
linter-php, v0.0.15
navigate, v0.1.6
symbol-gen, v1.0.0

# Dev
No dev packages
```

**Comment by renanmpimentel** [comment]
+1

**Comment by cortopy** [comment]
Same issue here

**Comment by Sobral** [comment]
+1

**Comment by Dennislampert** [comment]
+1

**Comment by alexsloan** [comment]
+1
