### ISSUE TITLE
Failed to activate the define-jump package

### ISSUE THREAD

**Issue by FlYos** [hughsk/atom-define-jump#2]
1. Fresh install of plugin
2. Open php file with this content `Illuminate\View\ViewServiceProvider::class` (laravel 5.1)
3. Run command on commande panel and .... `Failed to activate the define-jump package`

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [define-jump](git://github.com/hughsk/atom-define-jump) package, v1.0.1
### Stack Trace

Failed to activate the define-jump package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/Users/steven/.atom/packages/define-jump/index.js:15:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
```
### Commands

```
     -0:05.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:03.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 define-jump:to-original-definition (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "peacock-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
autocomplete-php, v0.3.6
csslint, v1.1.3
define-jump, v1.0.1
emmet, v2.3.11
highlight-line, v0.11.0
jslint, v1.4.0
language-blade, v0.14.0
language-docker, v1.1.3
language-smarty, v1.1.0
laravel, v0.7.0
linter-php, v0.0.15
peacock-syntax, v1.4.0
php-twig, v4.0.0
remote-edit, v1.8.4
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by mattandrews** [comment]
I get the same error (on OS X 10.10.4).

**Comment by cortopy** [comment]
Just realised this is the same issue as https://github.com/hughsk/atom-define-jump/issues/1
